version: "3.7"
services:


networks:
    eatchef:
        driver: bridge

services: 
    app:
        build:
            args:
                user: sammy
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: eatchef
        container_name: eatchef-app
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - eatchef
    db:
        image: mysql:5.7
        container_name: eatchef-db
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_DATABASE=eatchef
            - MYSQL_ROOT_PASSWORD=change_it
            - SERVICE_TAGS=dev
            - SERVICE_NAME=mysql
        networks:
            - eatchef
        ports: 
            - 3306:3306
    nginx:
        image: nginx:1.17-alpine
        container_name: eatchef-nginx
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - eatchef